# Dependabot configuration (v2)
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    rebase-strategy: auto
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      include: scope
    open-pull-requests-limit: 10
    groups:
      all-minor-patch:
        update-types: ["minor", "patch"]
      all-major:
        update-types: ["major"]
    labels: [dependencies, automerge]

  - package-ecosystem: github-actions
    directory: "/"
    rebase-strategy: auto
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(actions)
    open-pull-requests-limit: 10
    groups:
      all:
        patterns: ["*"]
    labels: [dependencies, automerge]
