name: Commitlint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    # Skip bot-authored dependency PRs and bot edits to those PRs
    # Commitlint failures on long Dependabot titles are noisy and non-blocking
    if: >
      github.event.pull_request.user.login != 'dependabot[bot]' &&
      !startsWith(github.head_ref, 'dependabot/') &&
      !startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.cjs
