name: Release Dry Run

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run package

      - name: Package VSIX
        run: npx --yes @vscode/vsce package

      - name: Compute names
        id: vars
        run: |
          NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")
          FILE="$NAME-$VERSION.vsix"
          TAG="autopathcomment-${VERSION}-dryrun-${GITHUB_RUN_NUMBER}"
          echo "file=$FILE" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.vars.outputs.file }}
          path: ${{ steps.vars.outputs.file }}

      - name: Create draft GitHub Release (dry-run)
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ steps.vars.outputs.tag }}
          name: ${{ steps.vars.outputs.tag }}
          generate_release_notes: true
          files: ${{ steps.vars.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

